Disambiguate which proc_macro import to use
If the syn crate is used with full features, compiling
async-stream results in an error.

error[E0432]: unresolved import `proc_macro`
 --> external/rust/crates/async-stream-impl/src/lib.rs:1:5
  |
1 | use proc_macro::TokenStream;
  |     ^^^^^^^^^^ help: a similar path exists: `syn::proc_macro`

error: aborting due to previous error

This error can be avoided by being explicit about which proc_macro
import to use.